// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220608.4

#pragma once
#include "winrt/VirtualCameraManager_WinRT.h"
namespace winrt::VirtualCameraManager_WinRT::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) BasicAugmentedMediaSourceCustomPropertyPayload_base : implements<D, VirtualCameraManager_WinRT::BasicAugmentedMediaSourceCustomPropertyPayload, winrt::VirtualCameraManager_WinRT::IPropertyPayload, I...>
    {
        using base_type = BasicAugmentedMediaSourceCustomPropertyPayload_base;
        using class_type = VirtualCameraManager_WinRT::BasicAugmentedMediaSourceCustomPropertyPayload;
        using implements_type = typename BasicAugmentedMediaSourceCustomPropertyPayload_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"VirtualCameraManager_WinRT.BasicAugmentedMediaSourceCustomPropertyPayload";
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_BASICAUGMENTEDMEDIASOURCECUSTOMPROPERTYPAYLOAD_XAML_G_H) || __has_include("BasicAugmentedMediaSourceCustomPropertyPayload.xaml.g.h")

#include "BasicAugmentedMediaSourceCustomPropertyPayload.xaml.g.h"

#else

namespace winrt::VirtualCameraManager_WinRT::implementation
{
    template <typename D, typename... I>
    using BasicAugmentedMediaSourceCustomPropertyPayloadT = BasicAugmentedMediaSourceCustomPropertyPayload_base<D, I...>;
}

#endif
